version: "3.7"

services:
  postgres-metabase:
    image: postgres:10.10-alpine
    container_name: pcm-postgres-metabase
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
    ports:
      - 5436:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  metabase-app:
    container_name: pcm-metabase-app
    image: metabase/metabase
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: pass_culture
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres-metabase
    depends_on:
      - postgres-metabase
    links:
      - postgres-metabase